import { cn } from "@/lib/utils";

import type { Metadata } from "next";
import { Footer, Navbar } from "./(home)/_components";

export const metadata: Metadata = {
  title: "Social Caption",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className=" px-0 overflow-clip w-full h-full flex flex-col">
      <Navbar />
      <div className="h-[calc(100vh-116px)] w-full overflow-xclip mt-[116px] overflow-auto flex flex-col">
        <div className="  ">{children}</div>
        <Footer />
      </div>
    </div>
  );
}
