import { cn } from "@/lib/utils";
import { GeistSans as FontSans } from "geist/font/sans";
import "@/styles/globals.css";

import type { Metadata } from "next";

export const fontSans = FontSans;

export const metadata: Metadata = {
  title: "Social Caption",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        {children}
      </body>
    </html>
  );
}
